name: ranking_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cupertino_icons: 1.0.6
  dio: 5.4.3+1
  easy_localization: 3.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: 5.1.0
  flutter_riverpod: 2.5.1
  freezed_annotation: 2.4.1
  get_it: 7.6.9
  injectable: 2.4.1
  json_annotation: 4.8.1
  meta: 1.11.0
  reactive_forms: 16.1.1
  reactive_forms_annotations: 4.3.0
  stack_trace: 1.11.1



dev_dependencies:
  build_runner: 2.4.9
  flutter_lints: 3.0.2
  flutter_test:
    sdk: flutter
  freezed: 2.5.2
  injectable_generator: 2.6.1
  json_serializable: 6.7.1
  reactive_forms_generator: 4.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - .env